import { NextRequest } from 'next/server';
process.env.DATABASE_URL = 'postgresql://postgres:123456@localhost:5432/workai_test_multi_org_ga';
process.env.DIRECT_URL = process.env.DATABASE_URL;
process.env.JWT_SECRET = 'test-secret-for-multi-org-ga';
const { PrismaClient } = await import('@prisma/client');
const db = new PrismaClient();
await db.$executeRawUnsafe('TRUNCATE TABLE "OrganizationMembership" CASCADE');
await db.$executeRawUnsafe('TRUNCATE TABLE "AgentToken" CASCADE');
await db.$executeRawUnsafe('TRUNCATE TABLE "AppUser" CASCADE');
await db.$executeRawUnsafe('TRUNCATE TABLE "Organization" CASCADE');
await db.$executeRawUnsafe('TRUNCATE TABLE "UserSession" CASCADE');
const orgA = await db.organization.create({ data: { name: 'Dbg A', slug: 'dbg-a', timezone: 'UTC', status: 'active' } });
const user = await db.appUser.create({ data: { email: 'dbg@test.local', name: 'Dbg', passwordHash: 'x', role: 'admin', organizationId: orgA.id } });
await db.organizationMembership.create({ data: { userId: user.id, organizationId: orgA.id, role: 'admin', status: 'ACTIVE' } });
const loginApi = await import('./src/app/api/auth/login/route.ts');
const req = new NextRequest('http://localhost:3000/api/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: 'dbg@test.local', password: 'x' }) });
const res = await loginApi.POST(req);
const text = await res.text();
console.log('STATUS', res.status);
console.log('BODY', text.slice(0, 500));
