-- Full-organization cutover: deterministic cutover boundary timestamp.
-- Column "cutoverAt" is now created with the InfrastructureMigration table in 20260909000000_org_infrastructure_change_requests
-- No action needed.